var game_data = {
    "cyberpunk-2077": {
        img_src: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/capsule_184x69.jpg?t=1607696821",
        name: "Cyberpunk 2077",
        price: "79.99",
        delux_name: "",
        delux_price: "",
        tags: "Cyberpunk, Open World, RPG, Futuristic, Sci-fi",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src: "https://cdn.cloudflare.steamstatic.com/steam/apps/256810255/movie480_vp9.webm?t=1605891166",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/ss_9beef14102f164fa1163536d0fb3a51d0a2e4a3f.600x338.jpg?t=1607696821",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/ss_ae4465fa8a44dd330dbeb7992ba196c2f32cabb1.600x338.jpg?t=1607696821",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/ss_ff3d920e254d18aa2a25d3765ac2ebe845efd208.600x338.jpg?t=1607696821",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/ss_0002f18563d313bdd1d82c725d411408ebf762b0.600x338.jpg?t=1607696821"
        ],
        desciption: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        all_reviews: "Mostly Positive",
        recent_reviews: "",
        review_percent: "79",
        release_date: "9 Dec, 2020",
        developer: "CD PROJECT RED",
        rating: "Mature 17+",
        about: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. You can customize your character’s cyberware, skillset and playstyle, and explore a vast city where the choices you make shape the story and the world around you.\nBecome a cyberpunk, an urban mercenary equipped with cybernetic enhancements and build your legend on the streets of Night City.\nEnter the massive open world of Night City, a place that sets new standards in terms of visuals, complexity and depth.\nTake the riskiest job of your life and go after a prototype implant that is the key to immortality.",
        steam: "https://store.steampowered.com/app/1091500/Cyberpunk_2077/",
        epic: "https://www.epicgames.com/store/en-US/product/cyberpunk-2077/home",
        gog: "https://www.gog.com/game/cyberpunk_2077"
    },
    "the-witcher-3-wild-hunt": {
        img_src: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/capsule_184x69.jpg?t=1607418742",
        name: "The Witcher 3: Wild Hunt",
        price: "55.99",
        delux_name: "The Witcher 3: Wild Hunt - Game of the Year Edition",
        delux_price: "69.99",
        tags: "Open World, RPG, Story Rich, Atmospheric",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256658589/movie480.webm?t=1528288687",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/ss_107600c1337accc09104f7a8aa7f275f23cad096.600x338.jpg?t=1607418742",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/ss_64eb760f9a2b67f6731a71cce3a8fb684b9af267.600x338.jpg?t=1607418742",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/ss_eda99e7f705a113d04ab2a7a36068f3e7b343d17.600x338.jpg?t=1607418742",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/ss_d5b80eb63c12a6484f26796f3e34410651bba068.600x338.jpg?t=1607418742",
        ],
        desciption:
            "As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world.",
        all_reviews: "Overwhelmingly Positive",
        recent_reviews: "Overwhelmingly Positive",
        release_date: "18 May, 2015",
        developer: "CD PROJEKT RED",
        review_percent: "98",
        rating: "Mature 17+",
        about: "The Witcher: Wild Hunt is a story-driven open world RPG set in a visually stunning fantasy universe full of meaningful choices and impactful consequences. In The Witcher, you play as professional monster hunter Geralt of Rivia tasked with finding a child of prophecy in a vast open world rich with merchant cities, pirate islands, dangerous mountain passes, and forgotten caverns to explore.",
        steam: "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
        epic: "https://www.epicgames.com/store/en-US/product/the-witcher-3-wild-hunt/home",
        gog: "https://www.gog.com/game/the_witcher_3_wild_hunt",
    },
    "iron-harvest": {
        img_src: "https://cdn.cloudflare.steamstatic.com/steam/apps/826630/capsule_184x69.jpg?t=1607604113",
        name: "Iron Harvest",
        price: "68.99",
        delux_name: "Iron Harvest Deluxe",
        delux_price: "95.99",
        tags: "Strategy, RTS, Base Building, Mechs, War",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src: "https://cdn.cloudflare.steamstatic.com/steam/apps/256800570/movie480_vp9.webm?t=1599823405",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/826630/ss_be949635c259194fdc77a90ddc64155c678512cf.600x338.jpg?t=1607604113",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/826630/ss_c1f78f1bd6235ad93e6cef4f29ab5eae9381b4be.600x338.jpg?t=1607604113",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/826630/ss_a2728deaa2555c354c7dbe440ab066186c6c8275.600x338.jpg?t=1607604113",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/826630/ss_84a6feed8a3628041f4afd586510fa778a344553.600x338.jpg?t=1607604113",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/826630/ss_56b6c1f4a667594fad9bf9c59dc367b8fa9d76db.600x338.jpg?t=1607604113"
        ],
        desciption:
            "A classic real-time strategy game with an epic single player campaign, multiplayer & coop, set in the alternate reality of 1920+",
        all_reviews: "Mostly Positive",
        recent_reviews: "Very Positive",
        release_date: "1 Sep, 2020",
        developer: "KING Art",
        review_percent: "74",
        rating: "-",
        about: "DeveloperKing Art GamesPublisherDeep SilverRelease DateNov 19, 2020TagsStrategyActionCasualRating–PlatformWindowsIron HarvestIron Harvest is a real-time strategy game (RTS) set in the alternate reality of 1920+, just after the end of the Great War. The Game lets you control giant dieselpunk mechs, combining epic singleplayer and coop campaigns as well as skirmishes with intense action on the battlefield for multiplayer fans, Iron Harvest is the classic real-time strategy games fans have been waiting for.\nTradition clashes with scientific and technological progress, while Europe is still recovering from the brutal battles of the World War. Cities are being rebuilt and in the countryside, the era of the Iron Harvest has begun. Farmers are uncovering the remains of the majestic walking machines that had fought on the battlefields of the Great War.\nIn the midst of this chaos, a new threat appears that will put Europe’s very existence at risk. Secret forces are putting everything they can towards destabilization of entire countries, determined to set the world on fire once again and finally seize control.\nIntense coop & Competitive multiplayer combat: In addition expect regular free updates during the season, including new singleplayer challenges, multiplayer maps and more to look forward to.\nFeatures:\nCLASSIC REAL-TIME STRATEGY AT ITS FINEST: Lead dozens of different unit types into battle, carefully utilize cover and blast entire buildings to shreds. Take your time to come up with a plan which allows for a wide range of tactics, including a stealth approach. Mechs. We got mechs. Lots of them.\nSTRONG SINGLE PLAYER CAMPAIGNS & ENGAGING STORY: Experience an epic overarching story, spanning more than 20 missions over three campaigns. Join nine charismatic heroes and their beastly companions in their adventures across Europe. Team-up with a friend and master all campaigns side-by-side in co-op.\nYOU ARE THE ONE IN FULL CONTROL: Command three diverse factions with over 40 unit types and 9 heroes with unique abilities. Setup skirmish and multiplayer matches any way you want. Configure your personal game interface and choose your favourite input controls.\nINTENSE COOP & COMPETITIVE MULTIPLAYER COMBAT: Competitive multiplayer with ladders, ranked matches & leagues. Choose from a vast selection of skirmish maps and challenge maps, available to play in singleplayer and coop.\nBUILD AND FORTIFY YOUR BASE: Conquer resource points, build your base and place fortifications to protect your unit production and research.",
        steam: "https://store.steampowered.com/app/826630/Iron_Harvest/",
        epic: "https://www.epicgames.com/store/en-US/product/iron-harvest/home",
        gog: "https://www.gog.com/game/iron_harvest"
    },
    "immortals-fenyx-rising": {
        img_src: "https://cdn2.unrealengine.com/ifr-epic-std-edition-thumbnail-1920x1080-uk-1920x1080-952060336.jpg?h=270&resize=1&w=480",
        name: "Immortals Fenyx Rising",
        price: "79.99",
        delux_name: "Immortals Fenyx Rising Gold Edition",
        delux_price: "134.99",
        tags: "Action, Adventure",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src: "https://staticctf.akamaized.net/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/79W09JZf7thFlMyS9JmLdW/693057fee79a9d0b3925d9f595e10901/IFR_-_Heacer_website_launch__low_.mp4",
        images: [
            "https://vulcan.dl.playstation.net/ap/rnd/202009/0400/cICP36R5ZBVm5hIOKcEkhuWH.jpg",
            "https://vulcan.dl.playstation.net/ap/rnd/202009/0400/Br6P082yi5vMXczS79mp41Ix.jpg",
            "https://vulcan.dl.playstation.net/ap/rnd/202009/0400/y1TsjgdKj3AFb0Z5qdjPuEzj.jpg"
        ],
        desciption: "Immortals Fenyx Rising brings grand mythological adventure to life. Play as Fenyx on a quest to save the Greek gods.",
        all_reviews: "Mostly Positive",
        recent_reviews: "Mostly Positive",
        release_date: "Dec 3, 2020",
        developer: "Ubisoft",
        review_percent: "78",
        rating: "Teen",
        about: "YOU ARE THE GODS' LAST HOPE: Play as Fenyx on a quest to save the Greek gods from a dark curse. Take on mythological beasts, master the legendary powers of the gods, and defeat Typhon, the deadliest Titan in Greek mythology, in an epic fight for the ages.\nCONFRONT MYTHOLOGICAL ENEMIES: Face off against legendary beasts like Cyclops, Medusa, or Minotaur, and confront them in fast-paced aerial and melee combat, combining your god-given abilities and weapons.\WIELD THE POWER OF GODS: The gods of Olympus have blessed you with gifts. Use them to fight mythical monsters, solve ancient puzzles, and explore the vast open world.",
        steam: "",
        epic: "https://www.epicgames.com/store/en-US/product/immortals-fenyx-rising/home#editions",
        gog: ""
    },
    "humankind": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1124300/capsule_184x69.jpg?t=1608138357",
        name: "HUMANKIND™",
        price: "79.99",
        delux_name: "HUMANKIND™ Digital Deluxe Edition",
        delux_price: "79.99",
        tags: "Strategy, Turn-Based Strategy, Historical, 4X",
        win: "True",
        mac: "True",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256805491/movie480_vp9.webm?t=1603296615",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1124300/ss_ab0c0aac439fc3f086524a946d5f0d8da6e89fc6.600x338.jpg?t=1608138357",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1124300/ss_bf23a23edae11104647ad58deff4388ffaf1f766.600x338.jpg?t=1608138357",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1124300/ss_67abce52d2ed9beab6d9b74def3ef6c76601cad1.600x338.jpg?t=1608138357",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1124300/ss_932ada329c1d0cbaa5f343e3cca95a6952ef992e.600x338.jpg?t=1608138357",
        ],
        desciption:
            "HUMANKIND™ is Amplitude Studios' magnum opus, a Historical Strategy game where YOU will re-write the entire narrative of humankind – a convergence of culture, history, and values that allows you to create a civilization that is as unique as you are. HOW FAR WILL YOU PUSH HUMANKIND?",
        all_reviews: "No user reviews",
        recent_reviews: "",
        review_percent: "No user reviews",
        release_date: "April 22nd 2021",
        developer: "AMPLITUDE Studios",
        rating: "Rating Pending",
        about:
            "HUMANKIND™ is a historical strategy game, where you’ll be re-writing the entire narrative of human history and combining cultures to create a civilization that’s as unique as you are.\nCREATE YOUR CIVILIZATION: Combine up to 60 historical cultures as you lead your people from the Ancient to the Modern Age. From humble origins as a Neolithic tribe, transition to the Ancient Era as the Babylonians, become the Classical era Mayans, the Medieval Umayyads, the Early Modern era British, and so on. Each culture will add its own special gameplay layer, leading to near-endless outcomes.\nMORE THAN HISTORY, IT’S YOUR STORY: Face historical events, take impactful moral decisions, and make scientific breakthroughs. Discover the natural wonders of the world or build the most remarkable creations of humankind. Each game element is historically authentic. Combine them to build your own vision of the world.\nLEAVE YOUR MARK ON THE WORLD: The journey matters more than destination. Fame is a new and unifying victory condition. Every great deed you accomplish, every moral choice you make, every battle won will build your fame and leave a lasting impact on the world. The player with the most fame will win the game. Will you be the one to leave the deepest mark on the world? \nMASTER TACTICAL BATTLES ON LAND, SEA & AIR: Each battle in HUMANKIND™ plays out like a mini turn-based board game on top of the actual world map. Unstack your armies and command each of your units, including the emblematic units of your culture and their special abilities. Construct siege weapons to besiege and occupy cities. Fight in large battles spanning multiple turns, and don’t hesitate to bring in reinforcements!\nCUSTOMIZE YOUR LEADER: In HUMANKIND™, you’ll be playing the leader of your society as an avatar that you create and customize! Your avatar will evolve visually over the course of the game as your civilization develops. You’ll also be able to level up your leader via a meta-progression system to unlock custom looks that you can showoff to strangers and friends alike in multiplayer matches up to 8 players.",
        steam: "https://store.steampowered.com/app/1124300/HUMANKIND/",
        epic: "https://www.epicgames.com/store/en-US/product/humankind/digital-deluxe",
        gog: "",
    },
    "outward": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/794260/capsule_184x69.jpg?t=1608035082",
        name: "Outward",
        price: "49.99",
        delux_name: "",
        delux_price: "",
        tags: "RPG, Open World, Survival, Co-op, Fantasy",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256746269/movie480.webm?t=1581696169",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/794260/ss_ceada7f2a93988c4389304d38814e3e6d1f8215b.600x338.jpg?t=1608035082",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/794260/ss_31c3692b34eb49cb709c6f13024ae83956decbe7.600x338.jpg?t=1608035082",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/794260/ss_8b347d148ca89b314a62592bf870708b2cd224d2.600x338.jpg?t=1608035082",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/794260/ss_7ae08cf0611a8e194ef5899b6a664f1bbd43b247.600x338.jpg?t=1608035082",
        ],
        desciption:
            "No remarkable journey is achieved without great effort. Outward is an open-world RPG where the cold of the night or an infected wound can be as dangerous as a predator lurking in the dark. Explore the vast world of Aurai, embark on memorable adventures alone or with your friend.",
        all_reviews: "Mostly Positive",
        recent_reviews: "Mostly Positive",
        review_percent: "75",
        release_date: "26 Mar, 2019",
        developer: "Nine Dots Studio",
        rating: "Mature 17+",
        about:
            "Outward delivers an immersive RPG experience coupled with survival gameplay, offering a deeply-rewarding challenge for the most avid gamers.\nAs an ordinary adventurer, you’ll not only have to hide or defend yourself against threatening creatures, but also brave the hazardous environmental conditions, protect yourself against infectious diseases, make sure you get enough sleep, and stay hydrated. Embark on perilous expeditions across untamed lands to reach new cities, undertake varied missions and discover hidden dungeons crawling with formidable enemies.\nIn order to survive in the dazzling yet deadly world of Aurai, you’ll have to be cunning, clever and prepared. Devise diverse strategies to defeat your foes and don’t neglect your basic needs, sharing your journey with a friend, locally or online.",
        steam: "https://store.steampowered.com/app/794260/Outward/",
        epic: "https://www.epicgames.com/store/en-US/product/outward/home",
        gog: "https://www.gog.com/game/outward",
    },
    "among-us": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/945360/capsule_184x69.jpg?t=1607727748",
        name: "Among Us",
        price: "5.69",
        delux_name: "",
        delux_price: "",
        tags: "Multiplayer, Online Co-op, Space, Survival, 2D",
        win: "True",
        mac: "True",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256758605/movie480.webm?t=1565291941",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/945360/ss_c80d2f3fab624b18d9531adc6957767a7fede100.600x338.jpg?t=1607727748",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/945360/ss_649e19ff657fa518d4c2b45bed7ffdc4264a4b3a.600x338.jpg?t=1607727748",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/945360/ss_eab32f16b59c005489c10f9063227ed7b54b31ec.600x338.jpg?t=1607727748",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/945360/ss_7ccc894b8f95091f608fa012450549091cce2423.600x338.jpg?t=1607727748",
        ],
        desciption:
            "An online and local party game of teamwork and betrayal for 4-10 players...in space!",
        all_reviews: "Overwhelmingly Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "96",
        release_date: "16 Nov, 2018",
        developer: "Innersloth",
        rating: "Everyone 10+",
        about:
            "Play with 4-10 player online or via local WiFi as you attempt to prepare your spaceship for departure, but beware as one or more random players among the Crew are Impostors bent on killing everyone!\nOriginally created as a party game, we recommend playing with friends at a LAN party or online using voice chat. Enjoy cross-platform play between Android, iOS and PC.",
        steam: "https://store.steampowered.com/app/945360/Among_Us/",
        epic: "",
        gog: "",
    },
    "ghostrunner": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1139900/capsule_184x69.jpg?t=1606131976",
        name: "Ghostrunner",
        price: "39.99",
        delux_name: "",
        delux_price: "",
        tags: "Action, Cyberpunk, First-Person, Fast-Paced",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256801081/movie480_vp9.webm?t=1600186187",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1139900/ss_6f7ea1399cdf74cfafb0ddbf397ccb1f04f2bb04.600x338.jpg?t=1606131976",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1139900/ss_b3685fcab4d6f60c9fd54ffe8757ccaaef803d9e.600x338.jpg?t=1606131976",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1139900/ss_8f6b985f8568ccca30ddfe28b9b26fcf4468eaa5.600x338.jpg?t=1606131976",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1139900/ss_4df66f282c6aed12f941b3f7eb4c6fc3de3a8ea8.600x338.jpg?t=1606131976",
        ],
        desciption:
            "Ghostrunner offers a unique single-player experience: fast-paced, violent combat, and an original setting that blends science fiction with post-apocalyptic themes. It tells the story of a world that has already ended and its inhabitants who fight to survive.",
        all_reviews: "Very Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "91",
        release_date: "27 Oct, 2020",
        developer: "One More Level, 3D Realms, Slipgate Ironworks",
        rating: "Mature 17+",
        about:
            "Ghostrunner is a hardcore FPP slasher packed with lightning-fast action, set in a grim, cyberpunk megastructure. Climb Dharma Tower, humanity’s last shelter, after a world-ending cataclysm. Make your way up from the bottom to the top, confront the tyrannical Keymaster, and take your revenge.\nThe streets of this tower city are full of violence. Mara the Keymaster rules with an iron fist and little regard for human life.\nAs resources diminish, the strong prey on the weak and chaos threatens to consume what little order remains. The decisive last stand is coming. A final attempt to set things right before mankind goes over the edge of extinction.\nAs the most advanced blade fighter ever created, you’re always outnumbered but never outclassed. Slice your enemies with a monomolecular katana, dodge bullets with your superhuman reflexes, and employ a variety of specialized techniques to prevail.",
        steam: "https://store.steampowered.com/app/1139900/Ghostrunner/",
        epic: "https://www.epicgames.com/store/en-US/product/ghostrunner/home",
        gog: "https://www.gog.com/game/ghostrunner",
    },
    "stardew-valley": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/capsule_184x69.jpg?t=1595525376",
        name: "Stardew Valley",
        price: "16.99",
        delux_name: "",
        delux_price: "",
        tags: "Farming Sim, Life Sim, RPG, Pixel Graphics",
        win: "True",
        mac: "True",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256660296/movie480.webm?t=1454099186",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/ss_b887651a93b0525739049eb4194f633de2df75be.600x338.jpg?t=1595525376",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/ss_9ac899fe2cda15d48b0549bba77ef8c4a090a71c.600x338.jpg?t=1595525376",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/ss_4fa0866709ede3753fdf2745349b528d5e8c4054.600x338.jpg?t=1595525376",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/ss_d836f0a5b0447fb6a2bdb0a6ac5f954949d3c41e.600x338.jpg?t=1595525376",
        ],
        desciption:
            "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?",
        all_reviews: "Overwhelmingly Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "97",
        release_date: "26 Feb, 2016",
        developer: "ConcernedApe",
        rating: "Everyone 10+",
        about:
            "Stardew Valley is an open-ended country-life RPG!\nYou've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home? It won't be easy. Ever since Joja Corporation came to town, the old ways of life have all but disappeared. The community center, once the town's most vibrant hub of activity, now lies in shambles. But the valley seems full of opportunity. With a little dedication, you might just be the one to restore Stardew Valley to greatness!",
        steam: "https://store.steampowered.com/app/413150/Stardew_Valley/",
        epic: "",
        gog: "https://www.gog.com/game/stardew_valley",
    },
    "red-dead-online": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1404210/capsule_184x69.jpg?t=1607544298",
        name: "Red Dead Online",
        price: "7.49",
        delux_name: "",
        delux_price: "",
        tags: "Action, Adventure, Multiplayer, Western, PvP",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256811949/movie480_vp9.webm?t=1606871607",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1404210/ss_d9df4417af3fb8689293dcfe984070df4800215f.600x338.jpg?t=1607544298",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1404210/ss_11910cbe7b91268b17351baf2720af4f39395c08.600x338.jpg?t=1607544298",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1404210/ss_f84914f1d33becb92037057e70f9699dda5c74e4.600x338.jpg?t=1607544298",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1404210/ss_5d630173ec9e53bd0c6740c6b34141718a2fd6a6.600x338.jpg?t=1607544298",
        ],
        desciption:
            "Step into the vibrant, ever-evolving world of Red Dead Online and experience life in frontier America. Chase down bounties, battle outlaw gangs and other players, hunt, fish and trade, search for exotic treasures, run Moonshine, and much more to discover in a world of astounding depth and detail.",
        all_reviews: "Mostly Positive",
        recent_reviews: "",
        review_percent: "79",
        release_date: "1 Dec, 2020",
        developer: "Rockstar Games",
        rating: "Mature 17+",
        about:
            "Step into the vibrant, ever-evolving world of Red Dead Online and experience life across frontier America.\nForge your own path as you battle lawmen, outlaw gangs and ferocious wild animals to build a life on the American frontier. Build a camp, ride solo or form a posse and explore everything from the snowy mountains in the North to the swamps of the South, from remote outposts to busy farms and bustling towns. Chase down bounties, hunt, fish and trade, search for exotic treasures, run your own underground Moonshine distillery, or become a Naturalist to learn the secrets of the animal kingdom and much more in a world of astounding depth and detail.\nJoin millions of fellow players in the American West, and experience a world now packed with years’ worth of new features, gameplay and additional enhancements.\nIncludes Red Dead Online. Red Dead Redemption 2: Story Mode must be purchased separately.",
        steam: "https://store.steampowered.com/app/1404210/Red_Dead_Online/",
        epic:
            "https://www.epicgames.com/store/en-US/product/red-dead-redemption-2/red-dead-online",
        gog: "",
    },
    "rimworld": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/294100/capsule_184x69.jpg?t=1594308831",
        name: "RimWorld",
        price: "39.99",
        delux_name: "RimWorld Name in Game Pack",
        delux_price: "56.99",
        tags: "Colony Sim, Base Building, Survival, Strategy",
        win: "True",
        mac: "True",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256731486/movie480.webm?t=1539788136",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/294100/ss_371726c10a1b640dbf748fa62a500d911ac62427.600x338.jpg?t=1594308831",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/294100/ss_c34c6c04b002454d8fee32ba52dca99c9cf1d76b.600x338.jpg?t=1594308831",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/294100/ss_6bee92494e0c4dc53ad69000f2b71128c23629d6.600x338.jpg?t=1594308831",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/294100/ss_3038f36d2a1da63ddf29f16a48ee27254ab9b53d.600x338.jpg?t=1594308831",
        ],
        desciption:
            "A sci-fi colony sim driven by an intelligent AI storyteller. Generates stories by simulating psychology, ecology, gunplay, melee combat, climate, biomes, diplomacy, interpersonal relationships, art, medicine, trade, and more.",
        all_reviews: "Overwhelmingly Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "98",
        release_date: "17 Oct, 2018",
        developer: "Ludeon Studios",
        rating: "Mature 17+",
        about:
            "RimWorld is a story generator. It’s designed to co-author tragic, twisted, and triumphant stories about imprisoned pirates, desperate colonists, starvation and survival. It works by controlling the “random” events that the world throws at you. Every thunderstorm, pirate raid, and traveling salesman is a card dealt into your story by the AI Storyteller. There are several storytellers to choose from. Randy Random does crazy stuff, Cassandra Classic goes for rising tension, and Phoebe Chillax likes to relax.",
        steam: "https://store.steampowered.com/app/294100/RimWorld/",
        epic: "https://www.epicgames.com/store/en-US/product/rimworld/home",
        gog: "https://www.gog.com/game/rimworld",
    },
    "sid-meiers-civilization-vi": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/capsule_184x69.jpg?t=1605815014",
        name: "Sid Meier’s Civilization® VI",
        price: "79.99",
        delux_name: "",
        delux_price: "",
        tags: "Strategy, Turn-Based Strategy, Historical, 4X",
        win: "True",
        mac: "True",
        linux: "True",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256672694/movie480.webm?t=1476736935",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/ss_36c63ebeb006b246cb740fdafeb41bb20e3b330d.600x338.jpg?t=1605815014",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/ss_cf53258cb8c4d283e52cf8dce3edf8656f83adc6.600x338.jpg?t=1605815014",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/ss_f501156a69223131ee8b12452f3003698334e964.600x338.jpg?t=1605815014",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/ss_2be9153a2633e671c283e2dbcec64e2e4543f66f.600x338.jpg?t=1605815014",
        ],
        desciption:
            "Civilization VI offers new ways to interact with your world, expand your empire across the map, advance your culture, and compete against history’s greatest leaders to build a civilization that will stand the test of time. Play as one of 20 historical leaders including Roosevelt (America) and Victoria (England).",
        all_reviews: "Very Positive",
        recent_reviews: "Very Positive",
        review_percent: "82",
        release_date: "21 Oct, 2016",
        developer: "Firaxis Games, Aspyr (Mac), Aspyr (Linux)",
        rating: "Everyone 10+",
        about:
            "Originally created by legendary game designer Sid Meier, Civilization is a turn-based strategy game in which you attempt to build an empire to stand the test of time. Become Ruler of the World by establishing and leading a civilization from the Stone Age to the Information Age. Wage war, conduct diplomacy, advance your culture, and go head-to-head with history’s greatest leaders as you attempt to build the greatest civilization the world has ever known.\nCivilization VI offers new ways to engage with your world: cities now physically expand across the map, active research in technology and culture unlocks new potential, and competing leaders will pursue their own agendas based on their historical traits as you race for one of five ways to achieve victory in the game.",
        steam:
            "https://store.steampowered.com/app/289070/Sid_Meiers_Civilization_VI/",
        epic:
            "https://www.epicgames.com/store/en-US/product/sid-meiers-civilization-vi/home",
        gog: "",
    },
    "no-manss-sky": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/capsule_184x69.jpg?t=1606325215",
        name: "No Man's Sky",
        price: "66.49",
        delux_name: "",
        delux_price: "",
        tags: "Open World, Open World Survival Craft, Space, Exploration",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256793348/movie480_vp9.webm?t=1595259339",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/ss_b31ffc0dfbacaa0f63edd9f0f8509f6cb437184b.600x338.jpg?t=1606325215",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/ss_1d0c758d6ab2d82a5ed8eea15a7c2a3d25bd3aa1.600x338.jpg?t=1606325215",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/ss_22ff11035ec5dcd555848780514b43f89ac48477.600x338.jpg?t=1606325215",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/ss_73c23329662e3b9c0d367ab3f6e742a4685074a4.600x338.jpg?t=1606325215",
        ],
        desciption:
            "No Man's Sky is a game about exploration and survival in an infinite procedurally generated universe.",
        all_reviews: "Mixed",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "65",
        release_date: "12 Aug, 2016",
        developer: "Hello Games",
        rating: "Teen",
        about:
            "Inspired by the adventure and imagination that we love from classic science-fiction, No Man's Sky presents you with a galaxy to explore, filled with unique planets and lifeforms, and constant danger and action.\nIn No Man's Sky, every star is the light of a distant sun, each orbited by planets filled with life, and you can go to any of them you choose. Fly smoothly from deep space to planetary surfaces, with no loading screens, and no limits. In this infinite procedurally generated universe, you'll discover places and creatures that no other players have seen before - and perhaps never will again.",
        steam: "https://store.steampowered.com/app/275850/No_Mans_Sky/",
        epic: "",
        gog: "https://www.gog.com/game/no_mans_sky",
    },
    "rocket-league": {
        img_src: "https://cdn.cloudflare.steamstatic.com/steam/apps/252950/capsule_184x69.jpg?t=1607530214",
        name: "Rocket League",
        price: "Free to Play",
        delux_name: "",
        delux_price: "",
        tags: "Co-op, Multiplayer, Single Player",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src: "https://cdn.cloudflare.steamstatic.com/steam/apps/256812983/movie480_vp9.webm?t=1607530204",
        images: ["https://cdn.cloudflare.steamstatic.com/steam/apps/252950/ss_9c3ebba8b765eab8d5cf7d7a71d0f7cd940ccca3.600x338.jpg?t=1607530214", "https://cdn.cloudflare.steamstatic.com/steam/apps/252950/ss_f35b9b7f3b1be72d108ee0127043a8f21c7a844b.600x338.jpg?t=1607530214", "https://cdn.cloudflare.steamstatic.com/steam/apps/252950/ss_ffa236899d9011fd984179ec01bd16caa82b9ac1.600x338.jpg?t=1607530214", "https://cdn.cloudflare.steamstatic.com/steam/apps/252950/ss_da11a6e6d36eda139b118ea69c71b31d957c8818.600x338.jpg?t=1607530214"],
        desciption:
            "Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition.",
        all_reviews: "Overwhelmingly Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "93",
        release_date: "23 Sep, 2020",
        developer: "Psyonix LLC",
        rating: "Everyone",
        about:
            "Download and compete in the high-octane hybrid of arcade-style soccer and vehicular mayhem! customize your car, hit the field, and compete in one of the most critically acclaimed sports games of all time! Download and take your shot!\nHit the field by yourself or with friends in 1v1, 2v2, and 3v3 Online Modes, or enjoy Extra Modes like Rumble, Snow Day, or Hoops. Unlock items in Rocket Pass, climb the Competitive Ranks, compete in Competitive Tournaments, complete Challenges, enjoy cross-platform progression and more! The field is waiting. Take your shot!",
        steam: "https://store.steampowered.com/app/252950/Rocket_League/",
        epic: "https://www.epicgames.com/store/en-US/product/rocket-league/home",
        gog: "",
    },
    "warframe": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/230410/capsule_184x69.jpg?t=1608135055",
        name: "Warframe",
        price: "Free to Play",
        delux_name: "",
        delux_price: "",
        tags: "Free to Play, Looter Shooter, Action, Co-op, PvE",
        win: "True",
        mac: "True",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256798416/movie480_vp9.webm?t=1598385993",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/230410/ss_2d79448091149a8cc790b62e7422615a011d015a.600x338.jpg?t=1608135055",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/230410/ss_a0bbf96bf2f5498f5625bdf67a28493365cf6d72.600x338.jpg?t=1608135055",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/230410/ss_3708c72116bdf5e9e306c1a9857c3f257b1011f5.600x338.jpg?t=1608135055",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/230410/ss_bdfbc36be7556f8a21773170b1663b31c53a46e4.600x338.jpg?t=1608135055",
        ],
        desciption:
            "Warframe is a cooperative free-to-play third person online action game set in an evolving sci-fi world.",
        all_reviews: "Very Positive",
        recent_reviews: "Very Positive",
        review_percent: "89",
        release_date: "25 Mar, 2013",
        developer: "Digital Extremes",
        rating: "Mature 17+",
        about: "An ever-evolving wasteland: The Cambion Drift continues to fester with unsightly challenges. Delve deep into unexplored Entrati Vault ruins as you take on new Bounties from Mother, fight toe-to-toe against the Infested Mitosid, and discover new conservation targets.\nGara Kaleida: Honor Gara’s unbreakable spirit with the stunning Gara Kaleida Collection! Features the Gara Kaleida Skin, Starglaze Shards, Glistor Syandana and Rephrax longsword Skin.\nThe Cambion Armaments Collection: Fight fire with fire using all-new Infested Weapons. Equip the Bubonico, a toxic Arm Cannon that fires both long and short-ranged projectiles, or splatter enemies with the bile-loaded Catabolyst Pistol. Find the full collection in the in-game Market!\nCHOOSE YOUR WARFRAME: With more than 30 Warframes, each fully customizable with their own unique abilities, you can create the perfect Warframe for you.\nASSEMBLE YOUR ARSENAL: Katanas. Crossbows. Flamethrowers. Expand your Arsenal with more than 300 diverse Weapons, then modify each one to match your playstyle.\nEXPERIENCE FAST-PACED COMBAT: Slice and dice through hordes of enemies, or go in guns blazing, or sneak your way in — the choice is yours.\n And More...",
        steam: "https://store.steampowered.com/app/230410/Warframe/",
        epic: "https://www.epicgames.com/store/en-US/product/warframe/home",
        gog: "",
    },
    "carrion": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/953490/capsule_184x69.jpg?t=1604081514",
        name: "Carrion",
        price: "22.79",
        delux_name: "CARRION: Deluxe Edition",
        delux_price: "45.77",
        tags: "Action, Indie, Villain Protagonist, Pixel Graphics",
        win: "True",
        mac: "True",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256793612/movie480_vp9.webm?t=1595426760",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/953490/ss_b4856724be6c68d0826ba09dd14f19e65df6d856.600x338.jpg?t=1604081514",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/953490/ss_bc3a3b3c8e037420b8dec8fbac29770041845247.600x338.jpg?t=1604081514",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/953490/ss_5f53d9ba6f95568c6ce39dad483a0e0d5a5dd457.600x338.jpg?t=1604081514",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/953490/ss_c3e32b7d65be51f55818d441b983fe3b42015edb.600x338.jpg?t=1604081514",
        ],
        desciption:
            "CARRION is a reverse horror game in which you assume the role of an amorphous creature of unknown origins, stalking and consuming those that imprisoned you.",
        all_reviews: "Very Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "93",
        release_date: "23 Jul, 2020",
        developer: "Phobia Game Studio",
        rating: "Mature 17+",
        about:
            "CARRION is a reverse horror game in which you assume the role of an amorphous creature of unknown origin. Stalk and consume those that imprisoned you to spread fear and panic throughout the facility. Grow and evolve as you tear down this prison and acquire more and more devastating abilities on the path to retribution.",
        steam: "https://store.steampowered.com/app/953490/CARRION/",
        epic: "https://www.epicgames.com/store/en-US/product/carrion/home",
        gog: "https://www.gog.com/game/carrion",
    },
    "roki": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1067540/capsule_184x69.jpg?t=1607081249",
        name: "Roki",
        price: "28.99",
        delux_name: "Roki Deluxe Edition",
        delux_price: "32.99",
        tags: "Casual, Third Person, Fantasy, Relaxing, Snow",
        win: "True",
        mac: "True",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256787897/movie480_vp9.webm?t=1591615525",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1067540/ss_77768a039846c40fd4932fc04af48039dc611895.600x338.jpg?t=1607081249",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1067540/ss_a263855ecf62decf8e1ab7f697ed4fe59bd260ef.600x338.jpg?t=1607081249",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1067540/ss_697f38fed14f3d998de4b869e6983683fb5cf7d2.600x338.jpg?t=1607081249",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/1067540/ss_16fbde8706bbc9e07a3d466bb404b7b8d3d2c031.600x338.jpg?t=1607081249",
        ],
        desciption:
            "Rediscover magic and chart your adventure through this forgotten northern world of mystery and monsters. Find your courage, discover hidden paths, solve ancient puzzles and travel deeper through the icy land to learn the truth.",
        all_reviews: "Very Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "95",
        release_date: "23 Jul, 2020",
        developer: "Polygon Treehouse",
        rating: "Everyone",
        about:
            "Rediscover magic and chart your adventure through this forgotten northern world of mystery and monsters. Find your courage, discover hidden paths, solve ancient puzzles and travel deeper through the icy land to learn the truth.\nJoin Tove on a fantastical journey to save her family; one that takes her deep into a hidden, long forgotten world of folklore, filled with strange locations and even stranger creatures. Explore the ancient wilderness, solve its mysteries, and save your family in this modern adventure game for all.",
        steam: "https://store.steampowered.com/app/1067540/Rki/",
        epic: "",
        gog: "https://www.gog.com/game/roki",
    },
    "the-messenger": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/764790/capsule_184x69.jpg?t=1582049935",
        name: "The Messenger",
        price: "22.79",
        delux_name: "",
        delux_price: "",
        tags: "Retro, Platformer, 2D, Ninja, Pixel Graphics",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256704437/movie480.webm?t=1534427206",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/764790/ss_8e0fa7f8226d8f8fd0dd313e26e6b4d97562f7a3.600x338.jpg?t=1582049935",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/764790/ss_245d381f3b4a280818c73ef3769a92ea3a5a23b7.600x338.jpg?t=1582049935",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/764790/ss_105fd3de6a4dbf2cb848f2c265212ae3eb7434e5.600x338.jpg?t=1582049935",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/764790/ss_8dd705de7ce4ae51d6f6c70fa577fbb3232c0ce0.600x338.jpg?t=1582049935",
        ],
        desciption:
            "As a demon army besieges his village, a young ninja ventures through a cursed world, to deliver a scroll paramount to his clan’s survival. What begins as a classic action platformer soon unravels into an expansive time-traveling adventure full of thrills, surprises, and humor.",
        all_reviews: "Very Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "94",
        release_date: "30 Aug, 2018",
        developer: "Sabotage",
        rating: "Everyone 10+",
        about:
            "As a demon army besieges his village, a young ninja ventures through a cursed world, to deliver a scroll paramount to his clan’s survival. What begins as a classic action platformer soon unravels into an expansive time-traveling adventure full of thrills, surprises, and humor.",
        steam: "https://store.steampowered.com/app/764790/The_Messenger/",
        epic: "https://www.epicgames.com/store/en-US/product/the-messenger/home",
        gog: "https://www.gog.com/game/the_messenger",
    },
    "desperados-iii": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/610370/capsule_184x69.jpg?t=1606513971",
        name: "Desperados III",
        price: "49.99",
        delux_name: "",
        delux_price: "",
        tags: "Strategy, Real Time Tactics, Stealth, Western",
        win: "True",
        mac: "True",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256791353/movie480_vp9.webm?t=1604430438",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/610370/ss_0278ff2c4d3a7bc4b2e2968f27b07db332d81edf.600x338.jpg?t=1606513971",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/610370/ss_63e3744aef636d584b7d4cd8dc98b2e6629192b2.600x338.jpg?t=1606513971",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/610370/ss_f6460db130b27d95f8fc883045a648c256db40c6.600x338.jpg?t=1606513971",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/610370/ss_94bf6cd34055f7219290e6191a124eaa9c40f6e3.600x338.jpg?t=1606513971",
        ],
        desciption:
            "Desperados III is a story-driven, hardcore tactical stealth game, set in a ruthless Wild West scenario. Play smart if you want to succeed. A good plan can make the difference between survival and finding yourself at the business end of a pistol.",
        all_reviews: "Overwhelmingly Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "96",
        release_date: "16 Jun, 2020",
        developer: "Mimimi Games",
        rating: "Mature 17+",
        about:
            "Desperados III is a story-driven, hardcore tactical stealth game, set in a ruthless Wild West scenario.\nIn this long-awaited prequel to the beloved classic Desperados: Wanted Dead or Alive, John Cooper will join forces with the runaway bride Kate, the shady hitman Doc McCoy, the giant trapper Hector, and Isabelle, a mysterious lady from New Orleans. On Cooper’s quest for redemption, his adventures lead him and his gang from rural towns, over swamps and riverbanks, and finally to a dramatic showdown worthy of Wild West legends.\nPlay smart if you want to succeed. A good plan can make the difference between survival and finding yourself at the business end of a pistol.",
        steam: "https://store.steampowered.com/app/610370/Desperados_III/",
        epic: "https://www.epicgames.com/store/en-US/product/desperados-3/home",
        gog: "https://www.gog.com/game/desperados_iii",
    },
    "divinity-original-sin-2---definitive-edition": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/435150/capsule_184x69.jpg?t=1607718127",
        name: "Divinity: Original Sin 2 - Definitive Edition",
        price: "54.99",
        delux_name: "Divinity: Original Sin 2 - Divine Edition",
        delux_price: "71.99",
        tags: "RPG, Choices Matter, Turn-Based Combat, PvP",
        win: "True",
        mac: "True",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256789813/movie480_vp9.webm?t=1592914188",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/435150/ss_b59e5889726cab2cf01a93d0c0d192d25928952a.600x338.jpg?t=1607718127",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/435150/ss_34a428cdd26113e8645b77331d9fc82fcc50a4a2.600x338.jpg?t=1607718127",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/435150/ss_66d58326ebea7154d7f3d89e02f13913452caef7.600x338.jpg?t=1607718127",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/435150/ss_d3badb07717f13ef3316928c513f8c4c7f7b50b1.600x338.jpg?t=1607718127",
        ],
        desciption:
            "The critically acclaimed RPG that raised the bar, from the creators of Baldur's Gate 3. Gather your party. Master deep, tactical combat. Venture as a party of up to four - but know that only one of you will have the chance to become a God.",
        all_reviews: "Overwhelmingly Positive",
        recent_reviews: "Overwhelmingly Positive",
        review_percent: "95",
        release_date: "14 Sep, 2017",
        developer: "Larian Studios",
        rating: "Mature 17+",
        about:
            "The Divine is dead. The Void approaches. And the powers lying dormant within you are soon to awaken. The battle for Divinity has begun. Choose wisely and trust sparingly; darkness lurks within every heart.\nA flesh-eating Elf, an Imperial Lizard or an Undead, risen from the grave? Discover how the world reacts differently to who - or what - you are.\nGather your party and develop relationships with your companions. Blast your opponents in deep, tactical, turn-based combat. Use the environment as a weapon, use height to your advantage, and manipulate the elements themselves to seal your victory.\nExplore the vast and layered world of Rivellon alone or in a party of up to 4 players in drop-in/drop-out cooperative play. Go anywhere, unleash your imagination, and explore endless ways to interact with the world. Beyond Rivellon, there’s more to explore in the brand-new PvP and Game Master modes.",
        steam:
            "https://store.steampowered.com/app/435150/Divinity_Original_Sin_2__Definitive_Edition/",
        epic: "",
        gog: "https://www.gog.com/game/divinity_original_sin_2",
    },
    "the-outer-worlds": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/578650/capsule_184x69.jpg?t=1607114988",
        name: "The Outer Worlds",
        price: "79.99",
        delux_name: "",
        delux_price: "",
        tags: "Action RPG, Open World, Exploration, FPS",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256806032/movie480_vp9.webm?t=1603463737",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/578650/ss_a1de8cccb606fa0896b42c127318c7a34d35a98a.600x338.jpg?t=1607114988",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/578650/ss_4fe162d9752bc89c2de14ba549ffb6a6260b09aa.600x338.jpg?t=1607114988",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/578650/ss_1467a74c1101f1a2a503a87568ace9a8b1f5a613.600x338.jpg?t=1607114988",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/578650/ss_1cc823f04b42e13a8cf479f4bf74e849cc289967.600x338.jpg?t=1607114988",
        ],
        desciption:
            "The Outer Worlds is an award-winning single-player RPG from Obsidian Entertainment and Private Division. As you explore a space colony, the character you decide to become will determine how this player-driven story unfolds. In the colony's corporate equation, you are the unplanned variable.",
        all_reviews: "Very Positive",
        recent_reviews: "Very Positive",
        review_percent: "86",
        release_date: "23 Oct, 2017",
        developer: "Obsidian Entertainment",
        rating: "Mature 17+",
        about:
            "The Outer Worlds is an award-winning single-player first-person sci-fi RPG from Obsidian Entertainment and Private Division.\nLost in transit while on a colonist ship bound for the furthest edge of the galaxy, you awake decades later only to find yourself in the midst of a deep conspiracy threatening to destroy the Halcyon colony. As you explore the furthest reaches of space and encounter various factions, all vying for power, the character you decide to become will determine how this player-driven story unfolds. In the corporate equation for the colony, you are the unplanned variable.\n",
        steam: "https://store.steampowered.com/app/578650/The_Outer_Worlds/",
        epic: "https://www.epicgames.com/store/en-US/product/the-outer-worlds/home",
        gog: "https://www.gog.com/game/the_outer_worlds"
    },
    "control-ultimate-edition": {
        img_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/capsule_184x69.jpg?t=1604045960",
        name: "Control Ultimate Edition",
        price: "54.99",
        delux_name: "",
        delux_price: "",
        tags: "Action, Adventure, Female Protagonist, Sci-fi",
        win: "True",
        mac: "False",
        linux: "False",
        trailer_src:
            "https://cdn.cloudflare.steamstatic.com/steam/apps/256795524/movie480_vp9.webm?t=1599146533",
        images: [
            "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/ss_8376498631b089e52fb5c75ffe119e0de5e6aed1.600x338.jpg?t=1604045960",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/ss_5a16ce565951479e142c56a23f19d88333d84945.600x338.jpg?t=1604045960",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/ss_c038bb7b20d72ba5d33cc95f7235aefa0b84a706.600x338.jpg?t=1604045960",
            "https://cdn.cloudflare.steamstatic.com/steam/apps/870780/ss_949cf39deee737fec3aadff903ec5311dd22bdab.600x338.jpg?t=1604045960",
        ],
        desciption:
            'Control Ultimate Edition contains the main game and all previously released Expansions ("The Foundation" and "AWE") in one great value package. Winner of over 80 awards, Control is a visually stunning third-person action-adventure that will keep you on the edge of your seat.',
        all_reviews: "Very Positive",
        recent_reviews: "Very Positive",
        review_percent: "91",
        release_date: "27 Aug, 2020",
        developer: "Remedy Entertainment",
        rating: "Mature 17+",
        about:
            "A corruptive presence has invaded the Federal Bureau of Control…Only you have the power to stop it. The world is now your weapon in an epic fight to annihilate an ominous enemy through deep and unpredictable environments. Containment has failed, humanity is at stake. Will you regain control?\nWinner of over 80 awards, Control is a visually stunning third-person action-adventure that will keep you on the edge of your seat. Blending open-ended environments with the signature world-building and storytelling of renowned developer, Remedy Entertainment, Control presents an expansive and intensely gratifying gameplay experience.\nCan you handle the bureau’s dark secrets? Unfold an epic supernatural struggle filled with unexpected characters and bizarre events, as you search for your missing brother, and discover the truth that has brought you here.",
        steam: "https://store.steampowered.com/app/870780/Control_Ultimate_Edition/",
        epic:
            "https://www.epicgames.com/store/en-US/product/control/ultimate-edition",
        gog: "https://www.gog.com/game/control_ultimate_edition",
    }
};